CREATE TABLE IF NOT EXISTS mysql_types (
    id                    bigint                  NOT NULL AUTO_INCREMENT,
    create_time           datetime                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           datetime(6)             NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    my_timestamp          timestamp               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    my_timestamp1         timestamp(1)            NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
    my_date               date                    NOT NULL DEFAULT '1970-01-01',
    my_time               time                    NOT NULL DEFAULT '00:00:00',
    my_time1              time(1)                 NOT NULL DEFAULT '00:00:00.0',


    name                  VARCHAR(200)            NOT NULL DEFAULT '',
    my_char               char(200)               NOT NULL DEFAULT '',
    my_binary             BINARY(60)              NOT NULL DEFAULT '0',
    my_var_binary         varbinary(60)           NOT NULL DEFAULT '0',

    my_bit                bit(64)                 NOT NULL DEFAULT B'00',
    my_bit20              bit(20)                 NOT NULL DEFAULT B'00',
    my_tinyint1           tinyint(1)              NOT NULL DEFAULT 0,
    my_tinyint            tinyint(3)              NOT NULL DEFAULT 0,
    my_tinyint_unsigned   tinyint UNSIGNED        NOT NULL DEFAULT 0,
    my_boolean            boolean                 NOT NULL DEFAULT FALSE,
    my_smallint           smallint                NOT NULL DEFAULT 0,
    my_smallint_unsigned  smallint UNSIGNED       NOT NULL DEFAULT 0,
    my_mediumint          mediumint               NOT NULL DEFAULT 0,
    my_mediumint_unsigned mediumint UNSIGNED      NOT NULL DEFAULT 0,
    my_int                int                     NOT NULL DEFAULT 0,
    my_int_unsigned       int UNSIGNED            NOT NULL DEFAULT 0,
    my_bigint             bigint                  NOT NULL DEFAULT 0,
    my_bigint_unsigned    bigint UNSIGNED         NOT NULL DEFAULT 0,
    my_decimal            decimal(14, 2)          NOT NULL DEFAULT 0.00,
    my_decimal_unsigned   decimal(14, 2) UNSIGNED NOT NULL DEFAULT 0.00,
    my_float              float                                                               NOT NULL DEFAULT 0.00,
    my_float_unsigned     float UNSIGNED                                                      NOT NULL DEFAULT 0.00,
    my_double             double                                                              NOT NULL DEFAULT 0.00,
    my_double_unsigned    double UNSIGNED                                                     NOT NULL DEFAULT 0.00,

    my_tiny_text          tinytext                                                            NULL,
    my_text               text                                                                NULL,
    my_medium_text        mediumtext                                                          NULL,
    my_long_text          longtext                                                            NULL,
    my_enum               enum ('T','F')                                                      NOT NULL DEFAULT 'F',
    my_set                set ('BEIJING','SHANGHAI','SHENZHEN','XIANGGANG','TAIBEI','AOMENG') NOT NULL DEFAULT 'BEIJING',
    my_json               json                                                                NULL,

    my_tinyblob           tinyblob                                                            NULL,
    my_blob               blob                                                                NULL,
    my_medium_blob        mediumblob                                                          NULL,
    my_long_blob          longblob                                                            NULL,

    my_geometry           geometry                                                            NULL,
    my_point              point                                                               NULL,
    my_linestring         LINESTRING                                                          NULL,
    my_polygon            POLYGON                                                             NULL,
    my_multipoint         MULTIPOINT                                                          NULL,
    my_multilinestring    MULTILINESTRING                                                     NULL,
    my_multipolygon       MULTIPOLYGON                                                        NULL,
    my_geometrycollection GEOMETRYCOLLECTION                                                  NULL,

    PRIMARY KEY (id)
)
