CREATE TABLE IF NOT EXISTS mysql_types (
    id                    bigint AUTO_INCREMENT,
    my_datetime           datetime                                                            NULL DEFAULT CURRENT_TIMESTAMP,
    my_datetime6          datetime(6)                                                         NULL DEFAULT CURRENT_TIMESTAMP(6),
    my_timestamp          timestamp                                                           NULL DEFAULT CURRENT_TIMESTAMP,
    my_timestamp1         timestamp(1)                                                        NULL DEFAULT CURRENT_TIMESTAMP(1),
    my_date               date                                                                NULL DEFAULT '1970-01-01',
    my_time               time                                                                NULL DEFAULT '00:00:00',
    my_time1              time(1)                                                             NULL DEFAULT '00:00:00.0',
    my_year               year                                                                NULL DEFAULT 1970,

    my_var_char200        VARCHAR(200)                                                        NULL DEFAULT '',
    my_char200            char(200)                                                           NULL DEFAULT '',
    my_binary60           BINARY(60)                                                          NULL DEFAULT '0',
    my_var_binary60       varbinary(60)                                                       NULL DEFAULT '0',

    my_bit64              bit(64)                                                             NULL DEFAULT B'00',
    my_bit20              bit(20)                                                             NULL DEFAULT B'00',
    my_tinyint1           tinyint(1)                                                          NULL DEFAULT 0,
    my_tinyint            tinyint                                                             NULL DEFAULT 0,
    my_tinyint_unsigned   tinyint UNSIGNED                                                    NULL DEFAULT 0,
    my_boolean            boolean                                                             NULL DEFAULT FALSE,
    my_smallint           smallint                                                            NULL DEFAULT 0,
    my_smallint_unsigned  smallint UNSIGNED                                                   NULL DEFAULT 0,
    my_mediumint          mediumint                                                           NULL DEFAULT 0,
    my_mediumint_unsigned mediumint UNSIGNED                                                  NULL DEFAULT 0,
    my_int                int                                                                 NULL DEFAULT 0,
    my_int_unsigned       int UNSIGNED                                                        NULL DEFAULT 0,
    my_bigint             bigint                                                              NULL DEFAULT 0,
    my_bigint_unsigned    bigint UNSIGNED                                                     NULL DEFAULT 0,
    my_decimal            decimal(14, 2)                                                      NULL DEFAULT 0.00,
    my_decimal_unsigned   decimal(14, 2) UNSIGNED                                             NULL DEFAULT 0.00,
    my_float              float                                                               NULL DEFAULT 0.00,
    my_float_unsigned     float UNSIGNED                                                      NULL DEFAULT 0.00,
    my_double             double                                                              NULL DEFAULT 0.00,
    my_double_unsigned    double UNSIGNED                                                     NULL DEFAULT 0.00,

    my_tiny_text          tinytext                                                            NULL,
    my_text               text                                                                NULL,
    my_medium_text        mediumtext                                                          NULL,
    my_long_text          longtext                                                            NULL,
    my_enum               enum ('T','F')                                                      NULL DEFAULT 'F',
    my_set                set ('BEIJING','SHANGHAI','SHENZHEN','XIANGGANG','TAIBEI','AOMENG') NULL DEFAULT 'BEIJING',
    my_json               json                                                                NULL,

    my_tiny_blob          tinyblob                                                            NULL,
    my_blob               blob                                                                NULL,
    my_medium_blob        mediumblob                                                          NULL,
    my_long_blob          longblob                                                            NULL,

    my_geometry           geometry                                                            NULL,
    my_point              point                                                               NULL,
    my_linestring         LINESTRING                                                          NULL,
    my_polygon            POLYGON                                                             NULL,
    my_multipoint         MULTIPOINT                                                          NULL,
    my_multilinestring    MULTILINESTRING                                                     NULL,
    my_multipolygon       MULTIPOLYGON                                                        NULL,
    my_geometrycollection GEOMETRYCOLLECTION                                                  NULL,

    PRIMARY KEY (id)
)
