package io.jdbd.mysql;

/**
 * @see <a href="https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html">Server SQL Modes</a>
 */
public enum SQLMode {

    ALLOW_INVALID_DATES,
    ANSI_QUOTES,
    ERROR_FOR_DIVISION_BY_ZERO,
    HIGH_NOT_PRECEDENCE,

    IGNORE_SPACE,
    NO_AUTO_VALUE_ON_ZERO,
    NO_BACKSLASH_ESCAPES,
    NO_DIR_IN_CREATE,

    NO_ENGINE_SUBSTITUTION,
    NO_UNSIGNED_SUBTRACTION,
    NO_ZERO_DATE,
    NO_ZERO_IN_DATE,

    ONLY_FULL_GROUP_BY,
    PAD_CHAR_TO_FULL_LENGTH,
    PIPES_AS_CONCAT,
    REAL_AS_FLOAT,

    STRICT_ALL_TABLES,
    STRICT_TRANS_TABLES,
    TIME_TRUNCATE_FRACTIONAL

}
