package io.jdbd.stmt;

import io.jdbd.AutoCloseable;
import io.jdbd.JdbdSQLException;
import io.jdbd.lang.Nullable;
import io.jdbd.result.ResultRow;
import io.jdbd.result.ResultStates;
import org.reactivestreams.Publisher;

import java.sql.BatchUpdateException;
import java.util.List;
import java.util.function.Consumer;

public interface ExecutableStatement extends Statement, AutoCloseable {

    /**
     * Adds a set of parameters to this <code>PreparedStatement</code>
     * object's batch of commands.
     *
     * @throws JdbdSQLException if a database access error occurs or
     *                          this method is called on a closed <code>PreparedStatement</code>
     */
    ExecutableStatement addBatch();

    /**
     * Submits a batch of commands to the database for execution and
     * if all commands execute successfully, returns an array of update counts.
     * The <code>int</code> elements of the array that is returned are ordered
     * to correspond to the commands in the batch, which are ordered
     * according to the order in which they were added to the batch.
     * The elements in the array returned by the method <code>executeBatch</code>
     * may be one of the following:
     * <OL>
     * <LI>A number greater than or equal to zero -- indicates that the
     * command was processed successfully and is an update count giving the
     * number of rows in the database that were affected by the command's
     * execution
     * <LI>A value of <code>SUCCESS_NO_INFO</code> -- indicates that the command was
     * processed successfully but that the number of rows affected is
     * unknown
     * <P>
     * If one of the commands in a batch update fails to execute properly,
     * this method throws a <code>BatchUpdateException</code>, and a JDBC
     * driver may or may not continue to process the remaining commands in
     * the batch.  However, the driver's behavior must be consistent with a
     * particular DBMS, either always continuing to process commands or never
     * continuing to process commands.  If the driver continues processing
     * after a failure, the array returned by the method
     * <code>BatchUpdateException.getUpdateCounts</code>
     * will contain as many elements as there are commands in the batch, and
     * at least one of the elements will be the following:
     *
     * <LI>A value of <code>EXECUTE_FAILED</code> -- indicates that the command failed
     * to execute successfully and occurs only if a driver continues to
     * process commands after a command fails
     * </OL>
     * <P>
     * The possible implementations and return values have been modified in
     * the Java 2 SDK, Standard Edition, version 1.3 to
     * accommodate the option of continuing to process commands in a batch
     * update after a <code>BatchUpdateException</code> object has been thrown.
     *
     * <p>
     * Flux throw {@link JdbdSQLException} if a database access error occurs,
     * this method is called on a closed <code>StaticStatement</code> or the
     * driver does not support batch statements. Throws {@link BatchUpdateException}
     * (a subclass of <code>JdbdSQLException</code>) if one of the commands sent to the
     * database fails to execute properly or attempts to return a result set.
     * </p>
     *
     * @return an {@link List} of update counts containing one element for each
     * command in the batch.  The elements of the array are ordered according
     * to the order in which commands were added to the batch.
     * @see PreparedStatement#addBatch()
     * @see StaticStatement#addBatch(String)
     * @see java.sql.PreparedStatement#executeBatch()
     */
    Publisher<Long> executeBatch();

    Publisher<ResultStates> executeBatchAsStates();

    /**
     * Executes the SQL statement in this <code>PreparedStatement</code> object,
     * which must be an SQL Data Manipulation Language (DML) statement, such as <code>INSERT</code>, <code>UPDATE</code> or
     * <code>DELETE</code>; or an SQL statement that returns nothing,
     * such as a DDL statement.
     *
     * <p>
     * Mono publish {@link JdbdSQLException}, if a database access error occurs;
     * this method is called on a closed  <code>PreparedStatement</code>
     * or the SQL statement returns a <code>ReactiveResultSet</code> object
     * </p>
     *
     * @return either (1) the row count for SQL Data Manipulation Language (DML) statements
     * or (2) 0 for SQL statements that return nothing
     * @see java.sql.PreparedStatement#executeUpdate()
     */
    Publisher<Long> executeUpdate();


    Publisher<ResultStates> executeUpdateAsStates();

    /**
     * Executes the SQL query in this <code>PreparedStatement</code> object
     * and returns the <code>ResultSet</code> object generated by the query.
     *
     * @return a <code>ResultSet</code> object that contains the data produced by the
     * query; never <code>null</code>
     * <p>
     * Flux throw {@link JdbdSQLException } if a database access error occurs;
     * this method is called on a closed  <code>PreparedStatement</code> or the SQL
     * statement does not return a <code>ResultSet</code> object
     * </p>
     * @see java.sql.PreparedStatement#executeQuery()
     */
    Publisher<ResultRow> executeQuery(Consumer<ResultStates> statesConsumer);


    /**
     * <p>
     * SQL parameter placeholder must be {@code ?}
     * </p>
     *
     * @param index         parameter placeholder index based zero.
     * @param nullableValue non null the parameter value
     */
    ExecutableStatement bind(int index, @Nullable Object nullableValue);

    boolean setFetchSize(int fetchSize);

}
